services:
  - type: web
    name: bookmymovie-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /