import time
import random
from datetime import datetime
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# --- CORRECTED IMPORT ---
# We need these imports for the event emission simulation printouts
# In a real app, these models would be imported from a shared events library.
from .event_models import PaymentSucceededEvent, PaymentFailedEvent 
# ------------------------

# --- Pydantic Models for API Contracts ---

class PaymentRequest(BaseModel):
    """Schema for a request to process payment for a hold."""
    hold_id: str = Field(..., example="HOLD_ABCDE", description="The seat hold ID to be paid for.")
    user_id: str = Field(..., example="USER_12345", description="The ID of the user confirming the payment.")
    amount: float = Field(..., gt=0, description="The total amount to be charged.")
    payment_token: str = Field(..., description="Tokenized payment info (e.g., card token from client).")

class PaymentResponse(BaseModel):
    """Schema for the result of a payment attempt."""
    transaction_id: str = Field(..., description="Unique transaction ID generated by this service.")
    status: str = Field(..., example="SUCCESS | FAILED", description="Final status of the payment attempt.")
    message: str = Field(..., example="Payment processed successfully.", description="Descriptive result message.")

# --- Helper Functions ---

def generate_transaction_id() -> str:
    """Generates a unique payment transaction ID."""
    return f"TXN_{int(time.time() * 1000)}{random.randint(100, 999)}"

# --- FastAPI Application Instance ---
app = FastAPI(
    title="Payment Microservice (Python/FastAPI)",
    description="Handles payment processing and emits success/failure events via the Message Broker (Mocked)."
)

# --- CORS Configuration ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allow all origins for development
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Service Health Check ---
@app.get("/health", status_code=200, summary="Service Health Check")
async def get_health():
    """
    Health Check Endpoint.
    Returns HTTP 200 OK if the service is running.
    """
    return {"status": "ok", "service": "payment"}

# --- API Endpoints ---

@app.post(
    "/v1/payments/process",
    response_model=PaymentResponse,
    summary="Initiate payment for a seat hold."
)
async def process_payment(request: PaymentRequest):
    """
    Simulates calling an external payment gateway and publishing the resulting event.
    
    If successful, the PaymentSucceededEvent triggers the Booking Service to confirm the booking.
    If failed, the PaymentFailedEvent triggers the Booking Service to release the hold (or rely on expiry).
    """
    transaction_id = generate_transaction_id()
    
    # Mock Payment Gateway Logic: 90% success rate
    if random.random() < 0.9:
        # Payment successful
        status_code = "SUCCESS"
        message = "Payment authorized and captured."
        
        # --- Event Emission Simulation: Payment Succeeded ---
        print("\n--- EMITTING KAFKA EVENT (PaymentSucceeded) ---")
        event = PaymentSucceededEvent(
            event_id=generate_transaction_id(), # Mock event ID
            source_service="PaymentService",
            transaction_id=transaction_id, 
            hold_id=request.hold_id, 
            user_id=request.user_id, 
            amount_paid=request.amount,
            payment_method="MockCard"
        )
        # Using model_dump_json for clean, standardized event payload output
        print(f"Event: {event.event_name}")
        print(f"Payload: {event.model_dump_json(indent=2)}")
        print("----------------------------------------------\n")
        
    else:
        # Payment failed
        status_code = "FAILED"
        message = "Payment authorization denied by bank or gateway error."

        # --- Event Emission Simulation: Payment Failed ---
        print("\n--- EMITTING KAFKA EVENT (PaymentFailed) ---")
        event = PaymentFailedEvent(
            event_id=generate_transaction_id(), # Mock event ID
            source_service="PaymentService",
            transaction_id=transaction_id, 
            hold_id=request.hold_id, 
            user_id=request.user_id, 
            reason=message
        )
        print(f"Event: {event.event_name}")
        print(f"Payload: {event.model_dump_json(indent=2)}")
        print("------------------------------------------\n")
        
    return PaymentResponse(
        transaction_id=transaction_id,
        status=status_code,
        message=message
    )
